// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8SPHfB40J322z4_3jQVVF_kEEM-LoySc',
    appId: '1:282793795955:web:ca47206fcae97d8fc72506',
    messagingSenderId: '282793795955',
    projectId: 'money-tracker-d6e1a',
    authDomain: 'money-tracker-d6e1a.firebaseapp.com',
    databaseURL: 'https://money-tracker-d6e1a-default-rtdb.firebaseio.com',
    storageBucket: 'money-tracker-d6e1a.appspot.com',
    measurementId: 'G-1EWJX45984',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4bUUZ6GZaJkNhPFCVIwcI5fitfEJa2OY',
    appId: '1:282793795955:android:35f17e9ead014780c72506',
    messagingSenderId: '282793795955',
    projectId: 'money-tracker-d6e1a',
    databaseURL: 'https://money-tracker-d6e1a-default-rtdb.firebaseio.com',
    storageBucket: 'money-tracker-d6e1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChv5L6ClWnbkPJskwfown0Dk34nKyYk1k',
    appId: '1:282793795955:ios:596b5505bc82967bc72506',
    messagingSenderId: '282793795955',
    projectId: 'money-tracker-d6e1a',
    databaseURL: 'https://money-tracker-d6e1a-default-rtdb.firebaseio.com',
    storageBucket: 'money-tracker-d6e1a.appspot.com',
    iosClientId: '282793795955-9jqr24hcso62avqi3uenfou99nhb75ea.apps.googleusercontent.com',
    iosBundleId: 'io.moresushant48.mo',
  );
}
